### ISSUE TITLE
login of existing users failes

### ISSUE THREAD

**Issue by reinethernal** [kevinoconnor7/osTicket-auth-mail#3]
#0 (корень)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
#1 (корень)/include/class.orm.php(3136): db_query('INSERT INTO `os...', true, true)
#2 (корень)/include/class.orm.php(597): MySqlExecutor->execute()
#3 (корень)/include/class.user.php(1019): VerySimpleModel->save(false)
#4 (корень)/include/class.client.php(459): UserAccount->save()
#5 (корень)/account.php(93): ClientAccount->update(Array, Array)
#6 {main}

**Comment by kevinoconnor7** [comment]
Unfortunately there's not a lot to go off of in the error trace without the full query.

I suspect that we might have a bunch of users in a bad state. Can you check to see if you have a bunch of unnamed users in existence? You might have to delete them or manually populate the missing fields (name/email).

I just published a [new version](https://github.com/kevinoconnor7/osTicket-auth-mail/releases/tag/v0.3) that properly populates the profile. Let me know if these two things fix your issue.

**Comment by reinethernal** [comment]
Thank you, Kevin. It helped, but partially.
Users can login, can change their data, but when they log out they are unable to login again.

And here's an error 

[29-Oct-2018 07:23:18 UTC] PHP Fatal error:  Call to a member function getId() on a non-object in /data/www/helpdesk-gumrf/html/include/class.client.php on line 209
[29-Oct-2018 07:23:18 UTC] PHP Stack trace:
[29-Oct-2018 07:23:18 UTC] PHP   1. {main}() /data/www/helpdesk-gumrf/html/login.php:0
[29-Oct-2018 07:23:18 UTC] PHP   2. AuthenticationBackend::process() /data/www/helpdesk-gumrf/html/login.php:52
[29-Oct-2018 07:23:18 UTC] PHP   3. MailClientAuthBackend->authenticate() /data/www/helpdesk-gumrf/html/include/class.auth.php:235
[29-Oct-2018 07:23:18 UTC] PHP   4. MailAuth->authenticate() phar:///data/www/helpdesk-gumrf/html/include/plugins/auth-mail.phar/mailauth.php:120
[29-Oct-2018 07:23:18 UTC] PHP   5. MailAuth->lookupOrCreate() phar:///data/www/helpdesk-gumrf/html/include/plugins/auth-mail.phar/mailauth.php:74
[29-Oct-2018 07:23:18 UTC] PHP   6. ClientSession->__construct() phar:///data/www/helpdesk-gumrf/html/include/plugins/auth-mail.phar/mailauth.php:57
[29-Oct-2018 07:23:18 UTC] PHP   7. EndUser->getId() /data/www/helpdesk-gumrf/html/include/class.usersession.php:123

**Comment by kevinoconnor7** [comment]
Pushed [a new version](https://github.com/kevinoconnor7/osTicket-auth-mail/releases/tag/v0.4) with a fix.
